---
- name: Setup for nfs server
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: make nfs_shared directory
      file:
        path: /home/ec2-user/nfs_shared
        state: directory
        mode: 0777                          

    - name: configure /etc/exports
      become: yes
      lineinfile:
        path: /etc/exports
        line: /home/ec2-user/nfs_shared 172.31.0.0/16(rw,sync)

    - name: nfs service restart
      become: yes
      service:
        name: nfs
        state: restarted

- name: Setup for nfs clients
  hosts: CentOS
  gather_facts: no

  tasks:
    - name: make nfs_client directory
      file:
        path: /home/ec2-user/nfs
        state: directory

    - name: mount point directory as client
      become: yes
      mount:
        path: /home/ec2-user/nfs
        src: 172.31.43.141:/home/ec2-user/nfs_shared
        fstype: nfs
        opts: nfsvers=3
        state: mounted
